#!/usr/bin/env bash
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(fd . ~/projects ~/projects/personal ~/projects/work/wdl ~/projects/work ~/.local ~/.config ~/ --min-depth 1 --max-depth 1 --type d --hidden | fzf)
fi
if [[ -z $selected ]]; then
    exit 0
fi
cd "$selected" || exit 1
