#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/projects ~/projects/personal ~/projects/study ~/projects/laradock-projects ~/projects/work ~/.local ~/.config/ ~/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    return 0
fi

cd "$selected" || exit 1

nvim .
